### PR TITLE
Added unit tests for takeByTopology in cpumanager.

### PR DESCRIPTION
**Pull request by ConnorDoyle**
- Moved takeByTopology to a new file.
- Made whole-socket, whole-core and cpu branches deterministic.
- Fixed a bug where asking for zero cpus yielded a nonempty cpuset.

cc @balajismaniam @sjenning

### CODE REVIEW

**Comment by ConnorDoyle** [comment]
Kudos to @balajismaniam for discovering bugs while writing node e2e tests

**Comment by sjenning** [comment]
lgtm :+1:

next time, if you can break the function relocation and function changes into separate commits, makes reviewing easier.  thanks!

tests ftw!

**Comment by ConnorDoyle** [comment]
going to close this and cherry-pick the commit to cpu-manager branch.

**Comment by balajismaniam** [comment]
LGTM.

**Comment by ConnorDoyle** [comment]
cherry-picked

**Pull request closed without merging**
